"""initialsss

Revision ID: 3de13e52b460
Revises: 30769de59168
Create Date: 2026-05-24 00:54:50.584398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de13e52b460'
down_revision: Union[str, Sequence[str], None] = '30769de59168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartitem', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cartitem', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cartitem', type_='foreignkey')
    op.drop_column('cartitem', 'user_id')
    # ### end Alembic commands ###
