"""add discription to expense

Revision ID: 124e620fc2a0
Revises: b3e965cdd88f
Create Date: 2026-05-20 13:02:49.816508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '124e620fc2a0'
down_revision: Union[str, Sequence[str], None] = 'b3e965cdd88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('discription', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'discription')
    # ### end Alembic commands ###
