"""sddd

Revision ID: dcdf85b28e49
Revises: d1a65db421df
Create Date: 2026-05-27 13:26:06.171063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcdf85b28e49'
down_revision: Union[str, Sequence[str], None] = 'd1a65db421df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('expense', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'updated_at')
    op.drop_column('expense', 'created_at')
    # ### end Alembic commands ###
