"""casecade added

Revision ID: f8f6c6d01e95
Revises: 124e620fc2a0
Create Date: 2026-05-20 13:39:39.899393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f6c6d01e95'
down_revision: Union[str, Sequence[str], None] = '124e620fc2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expense_user_email_fkey'), 'expense', type_='foreignkey')
    op.create_foreign_key(None, 'expense', 'user', ['user_email'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.create_foreign_key(op.f('expense_user_email_fkey'), 'expense', 'user', ['user_email'], ['email'])
    # ### end Alembic commands ###
